src/Sudoux/EagleBundle/Entity/EagleAssetAccount.php
<?php

namespace Sudoux\EagleBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;

/**
 * Class EagleAssetAccount
 * @package Sudoux\EagleBundle\Entity
 * @author Eric Haynes
 * @ExclusionPolicy("all")
 */
class EagleAssetAccount
{
    public  $types = array(
        0 => 'Checking',
        1 => 'Savings',
        2 => 'Money Market',
        3 => 'CD',
        4 => 'Mutual Fund',
        5 => 'Retirement',
        6 => 'Other',
    );



    /**
     * @var integer
     * @Expose()
     */
    private $id;

    /**
     * @var string
     * @Expose()
     */
    private $institution_name;

    /**
     * @var integer
     * @Expose()
     */
    private $type;

    /**
     * @var string
     * @Expose()
     */
    private $account_number;

    /**
     * @var float
     * @Expose()
     */
    private $balance;

    /**
     * @var
     * @author Eric Haynes
     */
    private $borrower;

    public function getTypeText()
    {
        if(isset($this->types)){
            return $this->types[$this->type];
        }
        return null;

    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set institution_name
     *
     * @param string $institutionName
     * @return EagleAssetAccount
     */
    public function setInstitutionName($institutionName)
    {
        $this->institution_name = $institutionName;
    
        return $this;
    }

    /**
     * Get institution_name
     *
     * @return string 
     */
    public function getInstitutionName()
    {
        return $this->institution_name;
    }

    /**
     * Set type
     *
     * @param integer $type
     * @return EagleAssetAccount
     */
    public function setType($type)
    {
        $this->type = $type;
    
        return $this;
    }

    /**
     * Get type
     *
     * @return integer 
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set account_number
     *
     * @param string $accountNumber
     * @return EagleAssetAccount
     */
    public function setAccountNumber($accountNumber)
    {
        $this->account_number = $accountNumber;
    
        return $this;
    }

    /**
     * Get account_number
     *
     * @return string 
     */
    public function getAccountNumber()
    {
        return $this->account_number;
    }

    /**
     * Set balance
     *
     * @param float $balance
     * @return EagleAssetAccount
     */
    public function setBalance($balance)
    {
        $this->balance = $balance;
    
        return $this;
    }

    /**
     * Get balance
     *
     * @return float 
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Set borrower
     *
     * @param \Sudoux\EagleBundle\Entity\EagleBorrower $borrower
     * @return EagleAssetAccount
     */
    public function setBorrower(\Sudoux\EagleBundle\Entity\EagleBorrower $borrower = null)
    {
        $this->borrower = $borrower;
    
        return $this;
    }

    /**
     * Get borrower
     *
     * @return \Sudoux\EagleBundle\Entity\EagleBorrower
     */
    public function getBorrower()
    {
        return $this->borrower;
    }
}

src/Sudoux/EagleBundle/Entity/EagleLoanDocument.php
<?php

namespace Sudoux\EagleBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;

/**
 * Class EagleLoanDocument
 * @package Sudoux\EagleBundle\Entity
 * @author Eric Haynes
 * @ExclusionPolicy("all")
 */
class EagleLoanDocument
{

    /**
     * @var array
     */
    public $statusValues = array(
        0 => 'New',
        1 => 'Not Submitted',
        2 => 'Awaiting Review',
        3 => 'Accepted',
        4 => 'Rejected'
    );

    /**
     * @var array
     */
    public $losStatusValues = array(
        0 => 'Not Sent',
        1 => 'Sent',
        2 => 'Pending Download',
        3 => 'Pending Upload',
        4 => 'Received',
        5 => 'Failed',
        6 => 'Queued',
    );


    /**
     * @var integer
     * @Expose()
     */
    private $id;

    /**
     * @var string
     * @Expose()
     */
    private $name;

    /**
     * @var string
     * @Expose()
     */
    private $extension;

    /**
     * @var integer
     * @Expose()
     */
    private $status;

    /**
     * @var boolean
     * @Expose()
     */
    private $required;

    /**
     * @var string
     * @Expose()
     */
    private $los_id;

    /**
     * @var integer
     * @Expose()
     */
    private $los_status;

    /**
     * @var \DateTime
     * @Expose()
     */
    private $created;

    /**
     * @var \Sudoux\Cms\FileBundle\Entity\File
     * @Expose()
     */
    private $file;

    /**
     * @var \Sudoux\Cms\TaxonomyBundle\Entity\Taxonomy
     * @Expose()
     */
    private $type;

    /**
     * @var \Doctrine\Common\Collections\Collection
     * @Expose()
     */
    private $loan;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->loan = new \Doctrine\Common\Collections\ArrayCollection();
        $this->status = 0;
        $this->created = new \DateTime();
        $this->required = false;
        $this->los_status = 0;
    }

    /**
     * @author Eric Haynes
     */
    public function serialize()
    {
        $document = new \stdClass();
        $document->name = $this->getFile()->getName();
        $document->filePath = $this->getFile()->getAbsolutePath();

    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return EagleLoanDocument
     */
    public function setName($name)
    {
        $this->name = $name;

        /// hack for late processing of the file. document should be subclass of file in next major release
        if(isset($this->file)) {
            $this->file->setName($name);
        }

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set extension
     *
     * @param string $extension
     * @return EagleLoanDocument
     */
    public function setExtension($extension)
    {
        $this->extension = $extension;
    
        return $this;
    }

    /**
     * Get extension
     *
     * @return string 
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * Set status
     *
     * @param integer $status
     * @return EagleLoanDocument
     */
    public function setStatus($status)
    {
        $this->status = $status;
    
        return $this;
    }

    /**
     * Get status
     *
     * @return integer 
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @return mixed
     * @author Eric Haynes
     */
    public function getStatusName()
    {
        return $this->statusValues[$this->status];
    }

    /**
     * Set required
     *
     * @param boolean $required
     * @return EagleLoanDocument
     */
    public function setRequired($required)
    {
        $this->required = $required;
    
        return $this;
    }

    /**
     * Get required
     *
     * @return boolean 
     */
    public function getRequired()
    {
        return $this->required;
    }

    /**
     * Set los_id
     *
     * @param string $losId
     * @return EagleLoanDocument
     */
    public function setLosId($losId)
    {
        $this->los_id = $losId;
    
        return $this;
    }

    /**
     * Get los_id
     *
     * @return string 
     */
    public function getLosId()
    {
        return $this->los_id;
    }

    /**
     * Set los_status
     *
     * @param integer $losStatus
     * @return EagleLoanDocument
     */
    public function setLosStatus($losStatus)
    {
        $this->los_status = $losStatus;
    
        return $this;
    }

    /**
     * Get los_status
     *
     * @return integer 
     */
    public function getLosStatus()
    {
        return $this->los_status;
    }

    /**
     * @return mixed
     * @author Eric Haynes
     */
    public function getLosStatusValue()
    {
        return $this->losStatusValues[$this->los_status];
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return EagleLoanDocument
     */
    public function setCreated($created)
    {
        $this->created = $created;
    
        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set file
     *
     * @param \Sudoux\Cms\FileBundle\Entity\File $file
     * @return EagleLoanDocument
     */
    public function setFile(\Sudoux\Cms\FileBundle\Entity\File $file = null)
    {
        $this->file = $file;
    
        return $this;
    }

    /**
     * Get file
     *
     * @return \Sudoux\Cms\FileBundle\Entity\File 
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Set type
     *
     * @param \Sudoux\Cms\TaxonomyBundle\Entity\Taxonomy $type
     * @return EagleLoanDocument
     */
    public function setType(\Sudoux\Cms\TaxonomyBundle\Entity\Taxonomy $type = null)
    {
        $this->type = $type;
    
        return $this;
    }

    /**
     * Get type
     *
     * @return \Sudoux\Cms\TaxonomyBundle\Entity\Taxonomy 
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Add loan
     *
     * @param \Sudoux\EagleBundle\Entity\EagleLoanApplication $loan
     * @return EagleLoanDocument
     */
    public function addLoan(\Sudoux\EagleBundle\Entity\EagleLoanApplication $loan)
    {
        $this->loan[] = $loan;
    
        return $this;
    }

    /**
     * Remove loan
     *
     * @param \Sudoux\EagleBundle\Entity\EagleLoanApplication $loan
     */
    public function removeLoan(\Sudoux\EagleBundle\Entity\EagleLoanApplication $loan)
    {
        $this->loan->removeElement($loan);
    }

    /**
     * Get loan
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getLoan()
    {
        return $this->loan;
    }
}

src/Sudoux/EagleBundle/Resources/views/EagleLoanApplicationAdmin/applicationNav.html.twig
{% if application.completed %}
	<div class="los-controls text-right">
	    <div class="btn-group">
    		<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
    			Export <span class="caret"></span>
    		</a>
    		<ul class="dropdown-menu text-left">
    			<li><a href="{{ path('sudoux_mortgage_admin_loan_export_fanniemae', { id: application.id }) }}" target="_blank">To Fannie Mae 3.2</a></li>
    			{# <li><a href="{{ path('sudoux_mortgage_admin_loan_export_mismo', { id: application.id }) }}" target="_blank">To MISMO</a></li> #}
    		</ul>
    	</div>
	</div>
{% endif %}
<div id="loan-application-admin-nav" class="loan-application-nav">

	<ul id="loan-application-admin-nav" class="nav-steps">
		<li class="{% if step == 1 %} active {% else %} completed clickable {% endif %}">
			<a href="{{ path('sudoux_mortgage_admin_loan_step1', { id: application.id }) }}">Borrower Info</a>
		</li>
		<li class="{% if step == 2 %} active {% elseif step > 2 %} completed {% endif %} {% if application.lastStepCompleted >= 1 %}clickable{% endif %}">
			<a href="{{ path('sudoux_mortgage_admin_loan_step2', { id: application.id }) }}">Property Info</a>
		</li>
		<li class="{% if step == 3 %} active {% elseif step > 3 %} completed {% endif %} {% if application.lastStepCompleted >= 2 %}clickable{% endif %}">
			<a href="{{ path('sudoux_mortgage_admin_loan_step3', { id: application.id }) }}">Employment</a>
		</li>
		<li class="{% if step == 4 %} active {% elseif step > 4 %} completed {% endif %} {% if application.lastStepCompleted >= 3 %}clickable{% endif %}">
			<a href="{{ path('sudoux_mortgage_admin_loan_step4', { id: application.id }) }}">Assets</a>
		</li>
		<li class="{% if step == 5 %} active  {% elseif step > 5 %} completed {% endif %} {% if application.lastStepCompleted >= 4 %}clickable{% endif %}">
			<a href="{{ path('sudoux_mortgage_admin_loan_step5', { id: application.id }) }}">Housing &amp; Income</a>
		</li>
		<li class="{% if step == 6 %} active  {% elseif step > 6 %} completed {% endif %} {% if application.lastStepCompleted >= 5 %}clickable{% endif %}">
			<a href="{{ path('sudoux_mortgage_admin_loan_step6', { id: application.id }) }}">Declarations</a>
		</li>
		<li class="{% if step == 7 %} active {% elseif step > 7 %} completed {% endif %} {% if application.lastStepCompleted >= 6 %}clickable{% endif %}">
			<a href="{{ path('sudoux_mortgage_admin_loan_step7', { id: application.id }) }}">Review</a>
		</li>
		{% if application.completed %}
			<li class="{% if step == 8 %} active {% endif %} clickable">
				<a href="{{ path('sudoux_mortgage_admin_loan_member', { id: application.id }) }}">Member Portal</a>
			</li>
		{% endif %}
	</ul>
</div>

src/Sudoux/EagleBundle/Resources/views/EagleLoanApplicationAdmin/applyStep7.html.twig
{% extends site.getAdminThemeTemplate('fullwidth.html.twig') %}

{% block title %}Loan Application{% endblock %}

{% block body_class %}page-loan-apply step7{% endblock %}

{% block head %}
	{% include 'SudouxMortgageBundle:LoanApplicationShared:loanApplicationHead.html.twig' %}
	<link rel="stylesheet" type="text/css" media="screen" href="{{ asset('bundles/sudouxcmstheme/lib/jquery/signaturepad/assets/jquery.signaturepad.css') }}" />
	<script src="{{ asset('bundles/sudouxcmstheme/lib/jquery/signaturepad/jquery.signaturepad.min.js') }}"></script>
	<script src="{{ asset('bundles/sudouxcmstheme/lib/jquery/signaturepad/assets/json2.min.js') }}"></script>
	<!--[if lt IE 9]><script src="{{ asset('bundles/sudouxcmstheme/lib/jquery/signaturepad/assets/flashcanvas.js') }}"></script><![endif]-->
{% endblock %}

{% block breadcrumb %}
	<ul class="breadcrumb">
		<li><a href="{{ path('sudoux_mortgage_admin_loan') }}">Loan Applications</a> <span class="divider">/</span></li>
		<li class="active">{{ block('title') }}</li>
	</ul>
{% endblock %}


{% block modal %}
	{% include 'SudouxMortgageBundle:LoanApplicationShared:borrowerDetailModal.html.twig' with { borrower: application.borrower } %}
		
	{% for borrower in application.coBorrower %}
		{% include 'SudouxMortgageBundle:LoanApplicationShared:borrowerDetailModal.html.twig' with { borrower: borrower } %}
	{% endfor %}
{% endblock %}

{% block content %}
	{% include 'SudouxMortgageBundle:LoanApplicationAdmin:applicationNav.html.twig' with { step: 7, application: application } %}
	<p>Please review your application</p>
	
	<div id="property-info-wrapper" class="well">
		<h3 class="title"><a href="{{ path('sudoux_mortgage_admin_loan_step2', { id: application.id }) }}" class="edit-link"><i class="icon-pencil"></i></a> Property Info</h3> 
		<div class="property-info">
			{% include 'SudouxMortgageBundle:LoanApplicationShared:loanSummary.html.twig' %}
		</div>
	</div>
	
	<div id="borrower-wrapper">
		<h3 class="title"><a href="{{ path('sudoux_mortgage_admin_loan_step1', { id: application.id }) }}" class="edit-link"><i class="icon-pencil"></i></a> Borrowers</h3> 
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Name</th>
					<th>Type</th>
					<th>SSN</th>
					<th>Birth Date</th>
					<th>View</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>{{ application.borrower.fullName }}</td>
					<td>Primary Borrower</td>
					<td>{{ application.borrower.ssn }}</td>
					<td>{{ application.borrower.birthDate|date(date_format) }}</td>
					<td><a href="#borrower-detail-modal-{{ application.borrower.id }}" class="btn btn-default" role="button" data-toggle="modal">View Details</a></td>
				</tr>
				{% for borrower in application.coBorrower %}
					<tr>
						<td>{{ borrower.fullName }}</td>
						<td>Co-Borrower</td>
						<td>{{ borrower.ssn }}</td>
						<td>{{ borrower.birthDate|date(date_format) }}</td>
						<td><a href="#borrower-detail-modal-{{ borrower.id }}" class="btn btn-default" role="button" data-toggle="modal">View Details</a></td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
				
	</div>

	<div id="title-info">
		<h3><a href="{{ path('sudoux_mortgage_admin_loan_step2', { id: application.id }) }}" class="edit-link"><i class="icon-pencil"></i></a> Title Info</h3>
		{% if application.titleCompany1 %}<b>Title Company #1:</b> {{ application.titleCompany1 }}<br>{% endif %}
		{% if application.titleCompany2 %}<b>Title Company #2:</b> {{ application.titleCompany2 }}<br>{% endif %}
		<b>Title Manner: </b> {{ application.titleManner }}
	</div>
	
	<div id="employment-wrapper">
		<h3 class="title"><a href="{{ path('sudoux_mortgage_admin_loan_step3', { id: application.id }) }}" class="edit-link"><i class="icon-pencil"></i></a> Employment</h3>
		{% set showEmployment = false %}
		{% for borrower in application.coBorrower %}
			{% if borrower.employment|length > 0 %}
				{% set showEmployment = true %}
			{% endif %}
		{% endfor %}
		{% if application.borrower.employment|length > 0 %}
			{% set showEmployment = true %}
		{% endif %}
		{% if showEmployment %}
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Borrower</th>
						<th>Employer</th>
						<th>Phone</th>
						<th>Position/Title</th>
						<th>Self Employed</th>
						<th>Time of Employment</th>
					</tr>
				</thead>
				<tbody>
					{% for employment in application.borrower.employment %}
						<tr>
							<td>{{ application.borrower.fullName }}</td>
							<td>
								<b>{{ employment.employerName }}</b><br>
								{{ employment.location.address1 }}<br>
								{{ employment.location.city }}, {{ employment.location.state.abbreviation }} {{ employment.location.zipcode }}
							</td>
							<td>{{ employment.employerPhone|phoneNumber }} {% if employment.employerPhoneExt %}Ext: {{ employment.employerPhoneExt }}{% endif %}</td>
							<td>{{ employment.title }}</td>
							<td>{{ employment.selfEmployed|boolToYesNo }}</td>
							<td>{{ employment.startDate|date(date_format) }} - {{ employment.endDate|date(date_format) }}</td>
						</tr>
					{% endfor %}
					{% for borrower in application.coBorrower %}
						{% for employment in borrower.employment %}
							<tr>
								<td>{{ borrower.fullName }}</td>
								<td>
									<b>{{ employment.employerName }}</b><br>
									{{ employment.location.address1 }}<br>
									{{ employment.location.city }}, {{ employment.location.state.abbreviation }} {{ employment.location.zipcode }}
								</td>
								<td>{{ employment.employerPhone|phoneNumber }} {% if employment.employerPhoneExt %}Ext: {{ employment.employerPhoneExt }}{% endif %}</td>
								<td>{{ employment.title }}</td>
								<td>{{ employment.selfEmployed|boolToYesNo }}</td>
								<td>{{ employment.startDate|date(date_format) }} - {{ employment.endDate|date(date_format) }}</td>
							</tr>
						{% endfor %}
					{% endfor %}
				</tbody>
			</table>
		{% else %}
			<p>None</p>
		{% endif %}
	</div>
	
	<div id="assets-wrapper">
		<h3 class="title"><a href="{{ path('sudoux_mortgage_admin_loan_step4', { id: application.id }) }}" class="edit-link"><i class="icon-pencil"></i></a> Account Assets</h3> 
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Borrower</th>
					<th>Institution Name</th>
					<th>Type of Account</th>
					<th>Account Number</th>
					<th>Balance</th>
				</tr>
			</thead>
			<tbody>		
				{% for asset in application.assetAccount %}
					<tr>
						<td>{{ asset.borrower.fullName }}</td>
						<td>{{ asset.institutionName }}</td>
						<td>{{ asset.typeText }}</td>
						<td>{{ asset.accountNumber }}</td>
						<td>${{ asset.balance|number_format }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		
		<h3 class="title"><a href="{{ path('sudoux_mortgage_admin_loan_step4', { id: application.id }) }}" class="edit-link"><i class="icon-pencil"></i></a> Real Estate Assets</h3>
		{% if application.assetRealEstate|length > 0 %}
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Borrower</th>
						<th>Location</th>
						<th>Market Value</th>
						<th>Amount of Mtg.</th>
						<th>Gross Rent</th>
						<th>Net Rent</th>
						<th>Mtg. Payment</th>
						<th>Ins/Tax/Exp</th>
					</tr>
				</thead>
				<tbody>		
					{% for asset in application.assetRealEstate %}
						<tr>
							<td>{{ asset.borrower.fullName }}</td>
							<td>{{ asset.location.address1 }}<br>{{ asset.location.city }}, {{ asset.location.state.abbreviation }} {{ asset.location.zipcode }}</td>
							<td>${{ asset.marketValue|number_format }}</td>
							<td>${{ asset.mortgageAmount|number_format }}</td>
							<td>${{ asset.mortgagePayment|number_format }}</td>
							<td>${{ asset.rentGrossIncome|number_format }}</td>
							<td>${{ asset.rentNetIncome|number_format }}</td>
							<td>${{ asset.insTaxExp|number_format }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		{% else %}
			<p>None</p>
		{% endif %}
	</div>
	
	<div id="housing-wrapper">
		<div id="housing-expenses">
			<h3 class="title">Housing Expenses</h3>
			
			<b>Rent:</b> ${{ application.expenseHousing.rent|number_format }}<br>
			<b>Mortgage:</b> ${{ application.expenseHousing.mortgage|number_format }}<br>
			<b>Other Financial:</b> ${{ application.expenseHousing.otherFinancial|number_format }}<br>
			<b>Hazard Insurance:</b> ${{ application.expenseHousing.insuranceHazard|number_format }}<br>
			<b>Insurance Mortgage:</b> ${{ application.expenseHousing.insuranceMortgage|number_format }}<br>
			<b>Real Estate Taxes:</b> ${{ application.expenseHousing.taxRealEstate|number_format }}<br>
			<b>HOA Dues:</b> ${{ application.expenseHousing.hoaDues|number_format }}<br>
			<b>Other:</b> ${{ application.expenseHousing.other|number_format }}
		</div>
		
		<h3 class="title">Monthly Income</h3>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Borrower</th>
					<th>Base</th>
					<th>Overtime</th>
					<th>Bonus</th>
					<th>Commission</th>
					<th>Interest</th>
					<th>Net Rent</th>
					<th>Other</th>
				</tr>
			</thead>
			<tbody>		
				{% for asset in application.incomeMonthly %}
					<tr>
						<td>{{ asset.borrower.fullName }}</td>
						<td>${{ asset.base|number_format }}</td>
						<td>${{ asset.overtime|number_format }}</td>
						<td>${{ asset.bonus|number_format }}</td>
						<td>${{ asset.commission|number_format }}</td>
						<td>${{ asset.interest|number_format }}</td>
						<td>${{ asset.rentNet|number_format }}</td>
						<td>${{ asset.other|number_format }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		
		{#}<h3 class="title"><a href="{{ path('sudoux_mortgage_admin_loan_step5', { id: application.id }) }}" class="edit-link"><i class="icon-pencil"></i></a> Other Income</h3>
		{% if application.incomeOther|length > 0 %}
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Source</th>
						<th>Description</th>
						<th>Amount</th>
					</tr>
				</thead>
				<tbody>		
					{% for asset in application.incomeOther %}
						<tr>
							<td>{{ asset.borrower.fullName }}</td>
							<td>{{ asset.description }}</td>
							<td>${{ asset.income|number_format }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		{% else %}
			<p>None</p>
		{% endif %}#}
	</div>

	{% import _self as helper %}
	{% macro badgeBool(bool) %}
		{% spaceless %}
			{% if bool %}
				<span class="label label-success">Y</span>
			{% else %}
				<span class="label label-important">N</span>
			{% endif %}
		{% endspaceless %}
	{% endmacro %}

	<div id="declarations-wrapper">
		<h3 class="title"><a href="{{ path('sudoux_mortgage_admin_loan_step6', { id: application.id }) }}" class="edit-link"><i class="icon-pencil"></i></a> Declarations</h3>
		<div >
			{% include 'SudouxMortgageBundle:LoanApplicationShared:declarationSummary.html.twig' with { borrower: application.borrower, form: form.borrower } %}
		</div>
		{% for coBorrower in application.coBorrower %}
			<div>
				{% include 'SudouxMortgageBundle:LoanApplicationShared:declarationSummary.html.twig' with { borrower: coBorrower, form: form.borrower } %}
			</div>
		{% endfor %}
	</div>

	<div id="govt-monitoring-wrapper">
		<h3 class="title"><a href="{{ path('sudoux_mortgage_admin_loan_step6', { id: application.id }) }}" class="edit-link"><i class="icon-pencil"></i></a> Government Monitoring</h3>
		<div>
			{% include 'SudouxMortgageBundle:LoanApplicationShared:governmentMonitoringSummary.html.twig' with { borrower: application.borrower } %}
		</div>
		{% for coBorrower in application.coBorrower %}
			<div>
				{% include 'SudouxMortgageBundle:LoanApplicationShared:governmentMonitoringSummary.html.twig' with { borrower: coBorrower } %}
			</div>
		{% endfor %}
	</div>
	<div id="comments-wrapper">
		<h3 class="title">Comments</h3>
		{{ form_widget(form.comments) }}
	</div>
	<form action="{{ path('sudoux_mortgage_admin_loan_step7', { id: application.id }) }}" method="post" novalidate="novalidate" class="loan-application-form">
		{% include 'SudouxMortgageBundle:LoanApplicationShared:acknowledgementAndAgreement.html.twig' %}
		<div class="text-center submit-wrapper">
			<div class="hide">{{ form_rest(form) }}</div>
	    	<a href="{{ path('sudoux_mortgage_admin_loan_step6', { id: application.id }) }}" class="btn btn-default">Back</a> <button type="submit" class="btn btn-default">Complete Application <span class="icon-ok-sign icon-white"></span></button>
	    </div>
	</form>
{% endblock %}